import React from 'react'
import one from "../../../assets/bestSellersProductFour.png"
import two from "../../../assets/bestSellersProductOne.png"
import three from "../../../assets/bestSellersProductThree.png"
import four from "../../../assets/bestSellersProductTwo.png"
import five from "../../../assets/ProductFour.png"
import six from "../../../assets/ProductOne.png"
import seven from "../../../assets/ProductThree.png"
import eight from "../../../assets/ProductTwo.png"
import nine from "../../../assets/specialOffersFour.png"
import ten from "../../../assets/specialOffersOne.png"
import eleven from "../../../assets/specialOffersThree.png"
import tweleve from "../../../assets/specialOffersTwo.png"



   export const images = [
        { id: 1, img: one, title: "imgOne" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 3, img: three, title: "imgThree" },
        { id: 4, img: four, title: "imgFour" },
        { id: 5, img: five, title: "imgFive" },
        { id: 6, img: six, title: "imgSix" },
        { id: 7, img: seven, title: "imgSeven" },
        { id: 8, img: eight, title: "imgEight" },
        { id: 9, img: nine, title: "imgNine" },
        { id: 10, img: ten, title: "imgTen" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 1, img: one, title: "imgOne" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 9, img: nine, title: "imgNine" },
        { id: 10, img: ten, title: "imgTen" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 1, img: one, title: "imgOne" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 3, img: three, title: "imgThree" },
        { id: 4, img: four, title: "imgFour" },
        { id: 5, img: five, title: "imgFive" },
        { id: 6, img: six, title: "imgSix" },
        { id: 7, img: seven, title: "imgSeven" },
        { id: 8, img: eight, title: "imgEight" },
        { id: 9, img: nine, title: "imgNine" },
        { id: 10, img: ten, title: "imgTen" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 3, img: three, title: "imgThree" },
        { id: 4, img: four, title: "imgFour" },
        { id: 5, img: five, title: "imgFive" },
        { id: 6, img: six, title: "imgSix" },
        { id: 7, img: seven, title: "imgSeven" },
        { id: 8, img: eight, title: "imgEight" },
        { id: 9, img: nine, title: "imgNine" },
        { id: 10, img: ten, title: "imgTen" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 1, img: one, title: "imgOne" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 3, img: three, title: "imgThree" },
        { id: 4, img: four, title: "imgFour" },
        { id: 5, img: five, title: "imgFive" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 3, img: three, title: "imgThree" },
        { id: 4, img: four, title: "imgFour" },
        { id: 5, img: five, title: "imgFive" },
        { id: 6, img: six, title: "imgSix" },
        { id: 6, img: six, title: "imgSix" },
        { id: 7, img: seven, title: "imgSeven" },
        { id: 8, img: eight, title: "imgEight" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 1, img: one, title: "imgOne" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 9, img: nine, title: "imgNine" },
        { id: 10, img: ten, title: "imgTen" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 8, img: eight, title: "imgEight" },
        { id: 9, img: nine, title: "imgNine" },
        { id: 10, img: ten, title: "imgTen" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 1, img: one, title: "imgOne" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 9, img: nine, title: "imgNine" },
        { id: 10, img: ten, title: "imgTen" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 1, img: one, title: "imgOne" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 3, img: three, title: "imgThree" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 3, img: three, title: "imgThree" },
        { id: 4, img: four, title: "imgFour" },
        { id: 5, img: five, title: "imgFive" },
        { id: 6, img: six, title: "imgSix" },
        { id: 7, img: seven, title: "imgSeven" },
        { id: 8, img: eight, title: "imgEight" },
        { id: 9, img: nine, title: "imgNine" },
        { id: 10, img: ten, title: "imgTen" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 3, img: three, title: "imgThree" },
        { id: 4, img: four, title: "imgFour" },
        { id: 5, img: five, title: "imgFive" },
        { id: 6, img: six, title: "imgSix" },
        { id: 7, img: seven, title: "imgSeven" },
        { id: 8, img: eight, title: "imgEight" },
        { id: 9, img: nine, title: "imgNine" },
        { id: 10, img: ten, title: "imgTen" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 1, img: one, title: "imgOne" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 3, img: three, title: "imgThree" },
        { id: 4, img: four, title: "imgFour" },
        { id: 5, img: five, title: "imgFive" },
        { id: 6, img: six, title: "imgSix" },
        { id: 7, img: seven, title: "imgSeven" },
        { id: 8, img: eight, title: "imgEight" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 1, img: one, title: "imgOne" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 9, img: nine, title: "imgNine" },
        { id: 8, img: eight, title: "imgEight" },
        { id: 9, img: nine, title: "imgNine" },
        { id: 10, img: ten, title: "imgTen" },
        { id: 11, img: eleven, title: "imgEleven" },
        { id: 12, img: tweleve, title: "imgTwelve" },
        { id: 1, img: one, title: "imgOne" },
        { id: 2, img: two, title: "imgTwo" },
        { id: 3, img: three, title: "imgThree" },
        { id: 4, img: four, title: "imgFour" },
        { id: 5, img: five, title: "imgFive" },

      
        
    ]




  
